### ISSUE TITLE
problem in web site builder.

### ISSUE THREAD

**Issue by dipakthoke** [LaunchKit/LaunchKit#20] opened 2016-08-16 09:40 UTC
I did the following step to built the web site in Launchkit
1. find the app on store.
2. upload the images on the local machine
3. click on save button.

when i click on save button  then it shows me errors. I have attach  the screenshots.

please help me to solve this problem.

![screenshot from 2016-08-16 15-08-49](https://cloud.githubusercontent.com/assets/18242209/17694843/79149014-63c3-11e6-8938-9306da5560a4.png)
![screenshot from 2016-08-16 15-09-06](https://cloud.githubusercontent.com/assets/18242209/17694850/7e0a8132-63c3-11e6-8a24-ad8e0a828a30.png)

**Comment by taylorhughes** [comment] 2016-09-24 21:28
Duplicate of #21, fixed

**Closed by taylorhughes** 2016-09-24 21:28 UTC
